# Generated by Django 2.2.9 on 2021-07-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210719_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='titel',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
